---
- name: Create admin users
  user:
    name: "{{ item }}"
    state: present
    shell: /bin/bash
    groups: "{{ 'sudo' if ansible_os_family == 'Debian' else 'wheel' }}"
    append: yes
    password: "$6$4CS6.aS8l16hcp8P$Y2mm3zgjU3Oe6U42N2Xpm0Gtm24gAzG0LYZTyvPggaT4Dvvl3R0HQJlJpp0eCFGO4nLLmvzgZPDdratJ2tYX9."
  loop:
    - admin_mendjargal
    - admin_yusunerdene
    - admin_bilegsaikhan

- name: Add admin users to sudo group (Debian)
  user:
    name: "{{ item }}"
    groups: sudo
    append: yes
  loop:
    - admin_mendjargal
    - admin_yusunerdene
    - admin_bilegsaikhan
  when: ansible_os_family == "Debian"

- name: Force password change on first login
  command: chage -d 0 {{ item }}
  loop:
    - admin_mendjargal
    - admin_yusunerdene
    - admin_bilegsaikhan

- name: Set password aging for admin users (ISO standard)
  command: chage -M 90 -m 1 -W 14 {{ item }}
  loop:
    - admin_mendjargal
    - admin_yusunerdene
    - admin_bilegsaikhan

- name: Add wheel group to sudoers (RHEL)
  lineinfile:
    path: /etc/sudoers
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) ALL'
    validate: 'visudo -cf %s'
  when: ansible_os_family == "RedHat"

- name: Copy scloud SSH key to admin users
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFawq1WbPc4sDOrrTy7iKOHjwU3xLO0yDAO/SyQyuJPI ansible-awx"
  loop:
    - admin_mendjargal
    - admin_yusunerdene
    - admin_bilegsaikhan
  ignore_errors: yes
