---
- name: Server Hardening Playbook
  hosts: all
  become: yes

  vars:
    admin_users:
      - admin_mendjargal
      - admin_yusunerdene
      - admin_bilegsaikhan
    admin_default_password_hash: "$6$rjeAxcwNFFHL/dEb$M5FNDZ1eY3i0v9oFAqiflPJuzF/xzB8vH491x5211SFRtbp8f4Sth41XdgKVkaQR98EsOUKry9infDPG/ndtx0"   # force changed on first login

  roles:
    - packages
    - ntp
    - ssh_hardening
    - cis_benchmark
    - password_policy
    - admin_users
